//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SecTypeSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_Wireframes.Screens;component/SampleData/SecTypeSampleDataSource/SecTypeSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _SecTypeCode = string.Empty;

		public string SecTypeCode
		{
			get
			{
				return this._SecTypeCode;
			}

			set
			{
				if (this._SecTypeCode != value)
				{
					this._SecTypeCode = value;
					this.OnPropertyChanged("SecTypeCode");
				}
			}
		}

		private string _SecTypeNameLong = string.Empty;

		public string SecTypeNameLong
		{
			get
			{
				return this._SecTypeNameLong;
			}

			set
			{
				if (this._SecTypeNameLong != value)
				{
					this._SecTypeNameLong = value;
					this.OnPropertyChanged("SecTypeNameLong");
				}
			}
		}

		private double _QuantityDisplayPrec = 0;

		public double QuantityDisplayPrec
		{
			get
			{
				return this._QuantityDisplayPrec;
			}

			set
			{
				if (this._QuantityDisplayPrec != value)
				{
					this._QuantityDisplayPrec = value;
					this.OnPropertyChanged("QuantityDisplayPrec");
				}
			}
		}

		private double _IsLongZeroMV = 0;

		public double IsLongZeroMV
		{
			get
			{
				return this._IsLongZeroMV;
			}

			set
			{
				if (this._IsLongZeroMV != value)
				{
					this._IsLongZeroMV = value;
					this.OnPropertyChanged("IsLongZeroMV");
				}
			}
		}

		private double _ValuationFactor = 0;

		public double ValuationFactor
		{
			get
			{
				return this._ValuationFactor;
			}

			set
			{
				if (this._ValuationFactor != value)
				{
					this._ValuationFactor = value;
					this.OnPropertyChanged("ValuationFactor");
				}
			}
		}

		private double _IsZeroCoupon = 0;

		public double IsZeroCoupon
		{
			get
			{
				return this._IsZeroCoupon;
			}

			set
			{
				if (this._IsZeroCoupon != value)
				{
					this._IsZeroCoupon = value;
					this.OnPropertyChanged("IsZeroCoupon");
				}
			}
		}

		private double _CanBeBoughtSold = 0;

		public double CanBeBoughtSold
		{
			get
			{
				return this._CanBeBoughtSold;
			}

			set
			{
				if (this._CanBeBoughtSold != value)
				{
					this._CanBeBoughtSold = value;
					this.OnPropertyChanged("CanBeBoughtSold");
				}
			}
		}

		private double _CanSplit = 0;

		public double CanSplit
		{
			get
			{
				return this._CanSplit;
			}

			set
			{
				if (this._CanSplit != value)
				{
					this._CanSplit = value;
					this.OnPropertyChanged("CanSplit");
				}
			}
		}

		private double _CanMature = 0;

		public double CanMature
		{
			get
			{
				return this._CanMature;
			}

			set
			{
				if (this._CanMature != value)
				{
					this._CanMature = value;
					this.OnPropertyChanged("CanMature");
				}
			}
		}

		private double _IsFFX = 0;

		public double IsFFX
		{
			get
			{
				return this._IsFFX;
			}

			set
			{
				if (this._IsFFX != value)
				{
					this._IsFFX = value;
					this.OnPropertyChanged("IsFFX");
				}
			}
		}

		private string _LongGainClassificationCode = string.Empty;

		public string LongGainClassificationCode
		{
			get
			{
				return this._LongGainClassificationCode;
			}

			set
			{
				if (this._LongGainClassificationCode != value)
				{
					this._LongGainClassificationCode = value;
					this.OnPropertyChanged("LongGainClassificationCode");
				}
			}
		}

		private string _IncomeTypeCode = string.Empty;

		public string IncomeTypeCode
		{
			get
			{
				return this._IncomeTypeCode;
			}

			set
			{
				if (this._IncomeTypeCode != value)
				{
					this._IncomeTypeCode = value;
					this.OnPropertyChanged("IncomeTypeCode");
				}
			}
		}

		private string _LongAssetClassCode = string.Empty;

		public string LongAssetClassCode
		{
			get
			{
				return this._LongAssetClassCode;
			}

			set
			{
				if (this._LongAssetClassCode != value)
				{
					this._LongAssetClassCode = value;
					this.OnPropertyChanged("LongAssetClassCode");
				}
			}
		}

		private string _ShortAssetClassCode = string.Empty;

		public string ShortAssetClassCode
		{
			get
			{
				return this._ShortAssetClassCode;
			}

			set
			{
				if (this._ShortAssetClassCode != value)
				{
					this._ShortAssetClassCode = value;
					this.OnPropertyChanged("ShortAssetClassCode");
				}
			}
		}

		private string _AmortizationMethodCode = string.Empty;

		public string AmortizationMethodCode
		{
			get
			{
				return this._AmortizationMethodCode;
			}

			set
			{
				if (this._AmortizationMethodCode != value)
				{
					this._AmortizationMethodCode = value;
					this.OnPropertyChanged("AmortizationMethodCode");
				}
			}
		}

		private string _AmortizeToCode = string.Empty;

		public string AmortizeToCode
		{
			get
			{
				return this._AmortizeToCode;
			}

			set
			{
				if (this._AmortizeToCode != value)
				{
					this._AmortizeToCode = value;
					this.OnPropertyChanged("AmortizeToCode");
				}
			}
		}

		private string _EMDRuleCode = string.Empty;

		public string EMDRuleCode
		{
			get
			{
				return this._EMDRuleCode;
			}

			set
			{
				if (this._EMDRuleCode != value)
				{
					this._EMDRuleCode = value;
					this.OnPropertyChanged("EMDRuleCode");
				}
			}
		}

		private string _FixedIncomeTypeCode = string.Empty;

		public string FixedIncomeTypeCode
		{
			get
			{
				return this._FixedIncomeTypeCode;
			}

			set
			{
				if (this._FixedIncomeTypeCode != value)
				{
					this._FixedIncomeTypeCode = value;
					this.OnPropertyChanged("FixedIncomeTypeCode");
				}
			}
		}

		private double _CanReinvestDividend = 0;

		public double CanReinvestDividend
		{
			get
			{
				return this._CanReinvestDividend;
			}

			set
			{
				if (this._CanReinvestDividend != value)
				{
					this._CanReinvestDividend = value;
					this.OnPropertyChanged("CanReinvestDividend");
				}
			}
		}

		private string _UseAvgCost = string.Empty;

		public string UseAvgCost
		{
			get
			{
				return this._UseAvgCost;
			}

			set
			{
				if (this._UseAvgCost != value)
				{
					this._UseAvgCost = value;
					this.OnPropertyChanged("UseAvgCost");
				}
			}
		}

		private double _IsVRS = 0;

		public double IsVRS
		{
			get
			{
				return this._IsVRS;
			}

			set
			{
				if (this._IsVRS != value)
				{
					this._IsVRS = value;
					this.OnPropertyChanged("IsVRS");
				}
			}
		}

		private double _UseSimpleInterestInLastPeriod = 0;

		public double UseSimpleInterestInLastPeriod
		{
			get
			{
				return this._UseSimpleInterestInLastPeriod;
			}

			set
			{
				if (this._UseSimpleInterestInLastPeriod != value)
				{
					this._UseSimpleInterestInLastPeriod = value;
					this.OnPropertyChanged("UseSimpleInterestInLastPeriod");
				}
			}
		}

		private double _IsInternal = 0;

		public double IsInternal
		{
			get
			{
				return this._IsInternal;
			}

			set
			{
				if (this._IsInternal != value)
				{
					this._IsInternal = value;
					this.OnPropertyChanged("IsInternal");
				}
			}
		}

		private double _UseConversionFactor = 0;

		public double UseConversionFactor
		{
			get
			{
				return this._UseConversionFactor;
			}

			set
			{
				if (this._UseConversionFactor != value)
				{
					this._UseConversionFactor = value;
					this.OnPropertyChanged("UseConversionFactor");
				}
			}
		}

		private double _IsHidden = 0;

		public double IsHidden
		{
			get
			{
				return this._IsHidden;
			}

			set
			{
				if (this._IsHidden != value)
				{
					this._IsHidden = value;
					this.OnPropertyChanged("IsHidden");
				}
			}
		}

		private string _PriceThruCode = string.Empty;

		public string PriceThruCode
		{
			get
			{
				return this._PriceThruCode;
			}

			set
			{
				if (this._PriceThruCode != value)
				{
					this._PriceThruCode = value;
					this.OnPropertyChanged("PriceThruCode");
				}
			}
		}

		private string _AlternativeAssetCode = string.Empty;

		public string AlternativeAssetCode
		{
			get
			{
				return this._AlternativeAssetCode;
			}

			set
			{
				if (this._AlternativeAssetCode != value)
				{
					this._AlternativeAssetCode = value;
					this.OnPropertyChanged("AlternativeAssetCode");
				}
			}
		}

		private string _PrincipalCurrencyCode = string.Empty;

		public string PrincipalCurrencyCode
		{
			get
			{
				return this._PrincipalCurrencyCode;
			}

			set
			{
				if (this._PrincipalCurrencyCode != value)
				{
					this._PrincipalCurrencyCode = value;
					this.OnPropertyChanged("PrincipalCurrencyCode");
				}
			}
		}

		private string _IncomeCurrencyCode = string.Empty;

		public string IncomeCurrencyCode
		{
			get
			{
				return this._IncomeCurrencyCode;
			}

			set
			{
				if (this._IncomeCurrencyCode != value)
				{
					this._IncomeCurrencyCode = value;
					this.OnPropertyChanged("IncomeCurrencyCode");
				}
			}
		}

		private string _RiskCountryCode = string.Empty;

		public string RiskCountryCode
		{
			get
			{
				return this._RiskCountryCode;
			}

			set
			{
				if (this._RiskCountryCode != value)
				{
					this._RiskCountryCode = value;
					this.OnPropertyChanged("RiskCountryCode");
				}
			}
		}

		private double _PaymentFrequencyID = 0;

		public double PaymentFrequencyID
		{
			get
			{
				return this._PaymentFrequencyID;
			}

			set
			{
				if (this._PaymentFrequencyID != value)
				{
					this._PaymentFrequencyID = value;
					this.OnPropertyChanged("PaymentFrequencyID");
				}
			}
		}

		private string _AccrualCalendarCode = string.Empty;

		public string AccrualCalendarCode
		{
			get
			{
				return this._AccrualCalendarCode;
			}

			set
			{
				if (this._AccrualCalendarCode != value)
				{
					this._AccrualCalendarCode = value;
					this.OnPropertyChanged("AccrualCalendarCode");
				}
			}
		}

		private double _PayOnMonthEnd = 0;

		public double PayOnMonthEnd
		{
			get
			{
				return this._PayOnMonthEnd;
			}

			set
			{
				if (this._PayOnMonthEnd != value)
				{
					this._PayOnMonthEnd = value;
					this.OnPropertyChanged("PayOnMonthEnd");
				}
			}
		}

		private double _TradeWithAI = 0;

		public double TradeWithAI
		{
			get
			{
				return this._TradeWithAI;
			}

			set
			{
				if (this._TradeWithAI != value)
				{
					this._TradeWithAI = value;
					this.OnPropertyChanged("TradeWithAI");
				}
			}
		}

		private double _CouponDelayDays = 0;

		public double CouponDelayDays
		{
			get
			{
				return this._CouponDelayDays;
			}

			set
			{
				if (this._CouponDelayDays != value)
				{
					this._CouponDelayDays = value;
					this.OnPropertyChanged("CouponDelayDays");
				}
			}
		}

		private double _SettlementLagDays = 0;

		public double SettlementLagDays
		{
			get
			{
				return this._SettlementLagDays;
			}

			set
			{
				if (this._SettlementLagDays != value)
				{
					this._SettlementLagDays = value;
					this.OnPropertyChanged("SettlementLagDays");
				}
			}
		}

		private double _HoldingPeriod = 0;

		public double HoldingPeriod
		{
			get
			{
				return this._HoldingPeriod;
			}

			set
			{
				if (this._HoldingPeriod != value)
				{
					this._HoldingPeriod = value;
					this.OnPropertyChanged("HoldingPeriod");
				}
			}
		}

		private double _SubjectToStateTax = 0;

		public double SubjectToStateTax
		{
			get
			{
				return this._SubjectToStateTax;
			}

			set
			{
				if (this._SubjectToStateTax != value)
				{
					this._SubjectToStateTax = value;
					this.OnPropertyChanged("SubjectToStateTax");
				}
			}
		}

		private double _SubjectToFederalTax = 0;

		public double SubjectToFederalTax
		{
			get
			{
				return this._SubjectToFederalTax;
			}

			set
			{
				if (this._SubjectToFederalTax != value)
				{
					this._SubjectToFederalTax = value;
					this.OnPropertyChanged("SubjectToFederalTax");
				}
			}
		}

		private string _DefaultSymbolTypeCode = string.Empty;

		public string DefaultSymbolTypeCode
		{
			get
			{
				return this._DefaultSymbolTypeCode;
			}

			set
			{
				if (this._DefaultSymbolTypeCode != value)
				{
					this._DefaultSymbolTypeCode = value;
					this.OnPropertyChanged("DefaultSymbolTypeCode");
				}
			}
		}

		private string _DefaultSymbolNameSpace = string.Empty;

		public string DefaultSymbolNameSpace
		{
			get
			{
				return this._DefaultSymbolNameSpace;
			}

			set
			{
				if (this._DefaultSymbolNameSpace != value)
				{
					this._DefaultSymbolNameSpace = value;
					this.OnPropertyChanged("DefaultSymbolNameSpace");
				}
			}
		}

		private double _IsExCouponBond = 0;

		public double IsExCouponBond
		{
			get
			{
				return this._IsExCouponBond;
			}

			set
			{
				if (this._IsExCouponBond != value)
				{
					this._IsExCouponBond = value;
					this.OnPropertyChanged("IsExCouponBond");
				}
			}
		}

		private double _ExCouponDayCount = 0;

		public double ExCouponDayCount
		{
			get
			{
				return this._ExCouponDayCount;
			}

			set
			{
				if (this._ExCouponDayCount != value)
				{
					this._ExCouponDayCount = value;
					this.OnPropertyChanged("ExCouponDayCount");
				}
			}
		}

		private string _ExCouponHolidayCode = string.Empty;

		public string ExCouponHolidayCode
		{
			get
			{
				return this._ExCouponHolidayCode;
			}

			set
			{
				if (this._ExCouponHolidayCode != value)
				{
					this._ExCouponHolidayCode = value;
					this.OnPropertyChanged("ExCouponHolidayCode");
				}
			}
		}

		private string _ExCouponDayRuleCode = string.Empty;

		public string ExCouponDayRuleCode
		{
			get
			{
				return this._ExCouponDayRuleCode;
			}

			set
			{
				if (this._ExCouponDayRuleCode != value)
				{
					this._ExCouponDayRuleCode = value;
					this.OnPropertyChanged("ExCouponDayRuleCode");
				}
			}
		}

		private string _CouponDelayRuleCode = string.Empty;

		public string CouponDelayRuleCode
		{
			get
			{
				return this._CouponDelayRuleCode;
			}

			set
			{
				if (this._CouponDelayRuleCode != value)
				{
					this._CouponDelayRuleCode = value;
					this.OnPropertyChanged("CouponDelayRuleCode");
				}
			}
		}

		private string _CouponDelayHolidayRuleCode = string.Empty;

		public string CouponDelayHolidayRuleCode
		{
			get
			{
				return this._CouponDelayHolidayRuleCode;
			}

			set
			{
				if (this._CouponDelayHolidayRuleCode != value)
				{
					this._CouponDelayHolidayRuleCode = value;
					this.OnPropertyChanged("CouponDelayHolidayRuleCode");
				}
			}
		}

		private double _IsTradingCash = 0;

		public double IsTradingCash
		{
			get
			{
				return this._IsTradingCash;
			}

			set
			{
				if (this._IsTradingCash != value)
				{
					this._IsTradingCash = value;
					this.OnPropertyChanged("IsTradingCash");
				}
			}
		}

		private double _IsTradable = 0;

		public double IsTradable
		{
			get
			{
				return this._IsTradable;
			}

			set
			{
				if (this._IsTradable != value)
				{
					this._IsTradable = value;
					this.OnPropertyChanged("IsTradable");
				}
			}
		}

		private double _IsBillable = 0;

		public double IsBillable
		{
			get
			{
				return this._IsBillable;
			}

			set
			{
				if (this._IsBillable != value)
				{
					this._IsBillable = value;
					this.OnPropertyChanged("IsBillable");
				}
			}
		}

		private double _IsUnsupervised = 0;

		public double IsUnsupervised
		{
			get
			{
				return this._IsUnsupervised;
			}

			set
			{
				if (this._IsUnsupervised != value)
				{
					this._IsUnsupervised = value;
					this.OnPropertyChanged("IsUnsupervised");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
