//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.CurrencySampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_Wireframes.Screens;component/SampleData/CurrencySampleDataSource/CurrencySampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _CurrencyCode = string.Empty;

		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}

			set
			{
				if (this._CurrencyCode != value)
				{
					this._CurrencyCode = value;
					this.OnPropertyChanged("CurrencyCode");
				}
			}
		}

		private string _ISOCode = string.Empty;

		public string ISOCode
		{
			get
			{
				return this._ISOCode;
			}

			set
			{
				if (this._ISOCode != value)
				{
					this._ISOCode = value;
					this.OnPropertyChanged("ISOCode");
				}
			}
		}

		private string _CurrencyName = string.Empty;

		public string CurrencyName
		{
			get
			{
				return this._CurrencyName;
			}

			set
			{
				if (this._CurrencyName != value)
				{
					this._CurrencyName = value;
					this.OnPropertyChanged("CurrencyName");
				}
			}
		}

		private string _CurrencySymbol = string.Empty;

		public string CurrencySymbol
		{
			get
			{
				return this._CurrencySymbol;
			}

			set
			{
				if (this._CurrencySymbol != value)
				{
					this._CurrencySymbol = value;
					this.OnPropertyChanged("CurrencySymbol");
				}
			}
		}

		private double _CurrencyPrecision = 0;

		public double CurrencyPrecision
		{
			get
			{
				return this._CurrencyPrecision;
			}

			set
			{
				if (this._CurrencyPrecision != value)
				{
					this._CurrencyPrecision = value;
					this.OnPropertyChanged("CurrencyPrecision");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
