//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ForwardRatesSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_Wireframes.Screens;component/SampleData/ForwardRatesSampleDataSource/ForwardRatesSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _CurrencyCode = string.Empty;

		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}

			set
			{
				if (this._CurrencyCode != value)
				{
					this._CurrencyCode = value;
					this.OnPropertyChanged("CurrencyCode");
				}
			}
		}

		private double _Bid30DayRate = 0;

		public double Bid30DayRate
		{
			get
			{
				return this._Bid30DayRate;
			}

			set
			{
				if (this._Bid30DayRate != value)
				{
					this._Bid30DayRate = value;
					this.OnPropertyChanged("Bid30DayRate");
				}
			}
		}

		private double _Bid60DayRate = 0;

		public double Bid60DayRate
		{
			get
			{
				return this._Bid60DayRate;
			}

			set
			{
				if (this._Bid60DayRate != value)
				{
					this._Bid60DayRate = value;
					this.OnPropertyChanged("Bid60DayRate");
				}
			}
		}

		private double _Bid90DayRate = 0;

		public double Bid90DayRate
		{
			get
			{
				return this._Bid90DayRate;
			}

			set
			{
				if (this._Bid90DayRate != value)
				{
					this._Bid90DayRate = value;
					this.OnPropertyChanged("Bid90DayRate");
				}
			}
		}

		private double _Bid180DayRate = 0;

		public double Bid180DayRate
		{
			get
			{
				return this._Bid180DayRate;
			}

			set
			{
				if (this._Bid180DayRate != value)
				{
					this._Bid180DayRate = value;
					this.OnPropertyChanged("Bid180DayRate");
				}
			}
		}

		private double _Bid360DayRate = 0;

		public double Bid360DayRate
		{
			get
			{
				return this._Bid360DayRate;
			}

			set
			{
				if (this._Bid360DayRate != value)
				{
					this._Bid360DayRate = value;
					this.OnPropertyChanged("Bid360DayRate");
				}
			}
		}

		private double _Source = 0;

		public double Source
		{
			get
			{
				return this._Source;
			}

			set
			{
				if (this._Source != value)
				{
					this._Source = value;
					this.OnPropertyChanged("Source");
				}
			}
		}

		private double _Bid720DayRate = 0;

		public double Bid720DayRate
		{
			get
			{
				return this._Bid720DayRate;
			}

			set
			{
				if (this._Bid720DayRate != value)
				{
					this._Bid720DayRate = value;
					this.OnPropertyChanged("Bid720DayRate");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
