//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.PortfoliosDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_Wireframes.Screens;component/SampleData/PortfoliosDataSource/PortfoliosDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _PortfolioCode = string.Empty;

		public string PortfolioCode
		{
			get
			{
				return this._PortfolioCode;
			}

			set
			{
				if (this._PortfolioCode != value)
				{
					this._PortfolioCode = value;
					this.OnPropertyChanged("PortfolioCode");
				}
			}
		}

		private string _Name1 = string.Empty;

		public string Name1
		{
			get
			{
				return this._Name1;
			}

			set
			{
				if (this._Name1 != value)
				{
					this._Name1 = value;
					this.OnPropertyChanged("Name1");
				}
			}
		}

		private string _Name2 = string.Empty;

		public string Name2
		{
			get
			{
				return this._Name2;
			}

			set
			{
				if (this._Name2 != value)
				{
					this._Name2 = value;
					this.OnPropertyChanged("Name2");
				}
			}
		}

		private string _Name3 = string.Empty;

		public string Name3
		{
			get
			{
				return this._Name3;
			}

			set
			{
				if (this._Name3 != value)
				{
					this._Name3 = value;
					this.OnPropertyChanged("Name3");
				}
			}
		}

		private string _StartDate = string.Empty;

		public string StartDate
		{
			get
			{
				return this._StartDate;
			}

			set
			{
				if (this._StartDate != value)
				{
					this._StartDate = value;
					this.OnPropertyChanged("StartDate");
				}
			}
		}

		private string _OwnedBy = string.Empty;

		public string OwnedBy
		{
			get
			{
				return this._OwnedBy;
			}

			set
			{
				if (this._OwnedBy != value)
				{
					this._OwnedBy = value;
					this.OnPropertyChanged("OwnedBy");
				}
			}
		}

		private string _CloseDate = string.Empty;

		public string CloseDate
		{
			get
			{
				return this._CloseDate;
			}

			set
			{
				if (this._CloseDate != value)
				{
					this._CloseDate = value;
					this.OnPropertyChanged("CloseDate");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
