//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SecTypeGroupSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Report { }
#else

	public class Report : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Report()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlew_Wireframes.Screens;component/SampleData/SecTypeGroupSampleDataSource/SecTypeGroupSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private RecordCollection _Data = new RecordCollection();

		public RecordCollection Data
		{
			get
			{
				return this._Data;
			}
		}
	}

	public class Record : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _SecTypeGroupID = 0;

		public double SecTypeGroupID
		{
			get
			{
				return this._SecTypeGroupID;
			}

			set
			{
				if (this._SecTypeGroupID != value)
				{
					this._SecTypeGroupID = value;
					this.OnPropertyChanged("SecTypeGroupID");
				}
			}
		}

		private string _SecTypeGroupNameLong = string.Empty;

		public string SecTypeGroupNameLong
		{
			get
			{
				return this._SecTypeGroupNameLong;
			}

			set
			{
				if (this._SecTypeGroupNameLong != value)
				{
					this._SecTypeGroupNameLong = value;
					this.OnPropertyChanged("SecTypeGroupNameLong");
				}
			}
		}

		private string _SecTypeGroupNameShort = string.Empty;

		public string SecTypeGroupNameShort
		{
			get
			{
				return this._SecTypeGroupNameShort;
			}

			set
			{
				if (this._SecTypeGroupNameShort != value)
				{
					this._SecTypeGroupNameShort = value;
					this.OnPropertyChanged("SecTypeGroupNameShort");
				}
			}
		}
	}

	public class RecordCollection : System.Collections.ObjectModel.ObservableCollection<Record>
	{ 
	}
#endif
}
